
# make_adaptor 配置参数
backbone_channel_list: [768, 384, 192, 96]
stages: [1, 2, 11, 2]
global_att_blocks: [7, 10, 13]
block: res
embed_dim: 96
dense_low_channels: [96, 48, 24]
window_spec: [8, 4, 14, 7]
use_sam_decoder: true
sam_ckpt_path: ./sam_spl/sam2_ckpt/sam2.1_hiera_small.pt
